### PR TITLE
Upgrade to babel 7.4 with core-js & minify preset

### PR DESCRIPTION
**Pull request by j15e**
I followed latest usage guides on https://babeljs.io/docs/en/usage to update the code.

It works for us with latest babel. They mostly removed / replaced polyfills with core-js runtime. 

See : https://github.com/babel/babel/issues/8416

### CODE REVIEW

**Comment by oliverfindl** [comment]
Thank you for your contribution!

Unfortunately, I don't like use of [babel-preset-minify](https://babeljs.io/docs/en/babel-preset-minify), which seems to be [abandoned](https://github.com/babel/minify/issues/952) in favor of [Terser](https://github.com/terser-js/terser). Additionally, `@babel/polyfill` should be removed and `core-js@3` should be added to `package.json`.

I'm not sure if [core-js](https://github.com/zloirock/core-js) should be also included in [src/index.js](https://github.com/oliverfindl/vue-svg-inline-loader/blob/ad9167f844aac539c37a6171f0d4cb1ced692d3d/src/index.js) and if [regenerator runtime](https://github.com/facebook/regenerator) is not required too, as stated in Babel docs ([here](https://babeljs.io/docs/en/usage#polyfill) and [here](https://babeljs.io/docs/en/babel-polyfill)). Whole this Babel madness was required for usage of `async/await` (and probably some more ES6+ features) in older node environments (more info [here](https://github.com/oliverfindl/vue-svg-inline-loader/issues/3)). I currently don't have such environment to test it out. This changes won't affect newer node environments, so it's required to test it in node 6+ (or maybe node 8+ should be enough according to [Node.js LTS schedule](https://nodejs.org/en/about/releases/), but still it will introduce breaking changes to node 6 environments...).

Please update and test your PR according my comments stated above and I can try to review it again.

At last, current version of loader should work as expected, only with deprecation warnings from `@babel/polyfill` (which are non-breakable as they are only in minor version).

Thanks

**Comment by j15e** [comment]
I've updated to minifying with terser, but stuff regarding babel, I'm pretty much lost at sea. I suggest you make other changes yourself if needed and amend my commit.

**Comment by oliverfindl** [comment]
Hello,

Don't want to sound rude, but [Terser](https://github.com/terser-js/terser) part of this issue is just top of iceberg. Not needed in first place, as it is only development dependency, so no need for minification. It was there only because Babel has [built-in option](https://babeljs.io/docs/en/options#minified) for it.

As for Babel, currently I don't have time to fiddle with it. Not to mention, it requires to setup multiple virtual machines with different Node.js environments.

I won't probably dive into this issue anytime soon. I might just edit `package.json` to use only minor version of Babel `7.2.x` or `7.3.x`, instead major version `7.x.x`.

I was also thinking about dropping support for older Node.js environments, but that would require to release new major version of this loader, which just does not sound right to me.

Thanks

**Comment by oliverfindl** [comment]
Closing this PR, because it isn't solving any real issue...

**Pull request closed without merging**
